name: Build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Build with all versions that can load the nashorn standalone Jar:
        java: [ 11, 12, 13 ]
    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Drun.jvmArguments="-Xmx4048m -Xms1024m"
      - uses: actions/upload-artifact@v2
        with:
          name: delight-nashorn-sandbox
          path: target/delight-nashorn-sandbox-*.jar

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 8, 9, 10, 11, 12, 13 ]
    name: Java ${{ matrix.java }} test
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: delight-nashorn-sandbox
      - name: Display structure of downloaded files
        run: ls -R
      - name: Clean unnecessary files
        run: 
          rm -rf delight-nashorn-sandbox-*-javadoc.jar
          rm -rf delight-nashorn-sandbox-*-sources.jar
# TODO: Validate JAR in some way ...

      
